services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "MinhaSenha123"
      ACCEPT_EULA: "Y"
      LANG: "en_US.UTF-8"
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
